// Zeus String Runtime Functions
// String primordial runtime functions for Zeus strings

const std = @import("std");
const abi = @import("abi.zig");
const runtime_util = @import("runtime_util.zig");

// ============================================================================
// Factory Functions (generated by codegen, declared here for runtime use)
// ============================================================================

/// Factory function to create a new u8[] array with given capacity
/// Generated by codegen as zeus_new_u8_array
extern fn zeus_new_u8_array(capacity: i32) *anyopaque;

/// Factory function to create a new string from a u8[] array
/// Generated by codegen as zeus_new_string
/// The parameter is the direct array pointer (not a pointer to pointer)
extern fn zeus_new_string(data: *anyopaque) *anyopaque;

// ============================================================================
// String Object ABI
// ============================================================================

/// Zeus string object layout
/// Matches the LLVM struct generated by codegen for the string class
/// Fields must match the order in GetStringPrimordialClassDefinition:
/// - obj_header (implicit)
/// - data (u8[] array)
/// - length (i32)
pub const ZeusStringObj = extern struct {
    obj_header: *abi.ZeusObjectHeader,
    data: ?*abi.ZeusArrayObj, // The u8[] array containing the string bytes
    length: i32, // Length of the string in bytes
};

/// Safely cast anyopaque pointer to ZeusStringObj pointer
pub inline fn castToStringObj(ptr: *anyopaque) *ZeusStringObj {
    return @as(*ZeusStringObj, @ptrCast(@alignCast(ptr)));
}

/// Helper to get string bytes from a ZeusStringObj
inline fn getStringBytes(str: *ZeusStringObj) ?[]const u8 {
    const array = str.data orelse return null;
    if (array.length == 0) return null;
    const data = array.data orelse return null;
    return @as([*]const u8, @ptrCast(@alignCast(data)))[0..array.length];
}

// ============================================================================
// Exported Runtime Functions
// ============================================================================

/// Constructor: zeus_string_constructor(this_ptr, return_buffer, bytes_ptr_ptr)
/// Creates a string object from a u8[] array
/// NOTE: bytes_ptr_ptr is a pointer to the array pointer (passed via alloca from wrapper)
export fn zeus_string_constructor(this_ptr: *anyopaque, return_buffer_ptr: ?*anyopaque, bytes_ptr_ptr: *anyopaque) callconv(.C) void {
    _ = return_buffer_ptr; // void return, not used

    const string_ptr = castToStringObj(this_ptr);

    // Dereference to get the actual ZeusArrayObj pointer
    const array_obj_ptr = @as(**anyopaque, @ptrCast(@alignCast(bytes_ptr_ptr))).*;
    const array_ptr = runtime_util.castToArrayObj(array_obj_ptr);

    // Store the u8[] reference directly in the string's data field
    string_ptr.data = array_ptr;
    // Set length from the array's length
    string_ptr.length = @intCast(array_ptr.length);
}

/// Compare two strings lexicographically
/// Returns: -1 if this < other, 0 if equal, 1 if this > other
export fn zeus_string_compare(this_ptr: *anyopaque, return_buffer_ptr_ptr: ?*anyopaque, other_ptr_ptr: *anyopaque) callconv(.C) void {
    const this_str = castToStringObj(this_ptr);

    // Dereference to get the other string pointer
    const other_obj_ptr = @as(**anyopaque, @ptrCast(@alignCast(other_ptr_ptr))).*;
    const other_str = castToStringObj(other_obj_ptr);

    const this_bytes = getStringBytes(this_str);
    const other_bytes = getStringBytes(other_str);

    var result: i8 = 0;

    if (this_bytes == null and other_bytes == null) {
        result = 0; // Both empty
    } else if (this_bytes == null) {
        result = -1; // This is empty, other is not
    } else if (other_bytes == null) {
        result = 1; // Other is empty, this is not
    } else {
        // Compare byte by byte
        const this_b = this_bytes.?;
        const other_b = other_bytes.?;
        const min_len = @min(this_b.len, other_b.len);

        var i: usize = 0;
        while (i < min_len) : (i += 1) {
            if (this_b[i] < other_b[i]) {
                result = -1;
                break;
            } else if (this_b[i] > other_b[i]) {
                result = 1;
                break;
            }
        }
        // If we didn't break (all compared bytes equal), compare lengths
        if (result == 0) {
            if (this_b.len < other_b.len) {
                result = -1;
            } else if (this_b.len > other_b.len) {
                result = 1;
            }
        }
    }

    // Write result using the Zeus return wrapper ABI
    if (runtime_util.allocateReturnBuffer(return_buffer_ptr_ptr, @sizeOf(i8))) |result_bytes| {
        result_bytes[0] = @as(u8, @bitCast(result));
    }
}

/// Check if two strings are equal
/// Returns: true if equal, false otherwise
export fn zeus_string_equals(this_ptr: *anyopaque, return_buffer_ptr_ptr: ?*anyopaque, other_ptr_ptr: *anyopaque) callconv(.C) void {
    const this_str = castToStringObj(this_ptr);

    // Dereference to get the other string pointer
    const other_obj_ptr = @as(**anyopaque, @ptrCast(@alignCast(other_ptr_ptr))).*;
    const other_str = castToStringObj(other_obj_ptr);

    var result: bool = false;

    // Quick length check first
    if (this_str.length != other_str.length) {
        result = false;
    } else {
        const this_bytes = getStringBytes(this_str);
        const other_bytes = getStringBytes(other_str);

        if (this_bytes == null and other_bytes == null) {
            result = true; // Both empty
        } else if (this_bytes == null or other_bytes == null) {
            result = false; // One is empty, other is not
        } else {
            // Compare bytes using std.mem.eql
            result = std.mem.eql(u8, this_bytes.?, other_bytes.?);
        }
    }

    // Write result using the Zeus return wrapper ABI
    if (runtime_util.allocateReturnBuffer(return_buffer_ptr_ptr, @sizeOf(bool))) |result_bytes| {
        result_bytes[0] = if (result) 1 else 0;
    }
}

/// Concatenate two strings and return a new string
/// Returns: A new string containing this + other
export fn zeus_string_concat(this_ptr: *anyopaque, return_buffer_ptr_ptr: ?*anyopaque, other_ptr_ptr: *anyopaque) callconv(.C) void {
    const this_str = castToStringObj(this_ptr);

    // Dereference to get the other string pointer
    const other_obj_ptr = @as(**anyopaque, @ptrCast(@alignCast(other_ptr_ptr))).*;
    const other_str = castToStringObj(other_obj_ptr);

    // Get lengths
    const len1: i32 = this_str.length;
    const len2: i32 = other_str.length;
    const total_len: i32 = len1 + len2;

    // Create a new u8[] array with the combined capacity
    const new_array_ptr = zeus_new_u8_array(total_len);
    const new_array = runtime_util.castToArrayObj(new_array_ptr);

    // Copy bytes from both strings into the new array
    if (new_array.data) |dest_data| {
        const dest = @as([*]u8, @ptrCast(@alignCast(dest_data)));

        // Copy this string's bytes
        if (this_str.data) |this_data| {
            if (this_data.data) |src| {
                const src_bytes = @as([*]const u8, @ptrCast(@alignCast(src)));
                @memcpy(dest[0..@as(usize, @intCast(len1))], src_bytes[0..@as(usize, @intCast(len1))]);
            }
        }

        // Copy other string's bytes at offset len1
        if (other_str.data) |other_data| {
            if (other_data.data) |src| {
                const src_bytes = @as([*]const u8, @ptrCast(@alignCast(src)));
                const offset: usize = @intCast(len1);
                const len2_usize: usize = @intCast(len2);
                @memcpy(dest[offset .. offset + len2_usize], src_bytes[0..len2_usize]);
            }
        }

        // Set the length of the new array
        new_array.length = @intCast(total_len);
    }

    // Create a new string from the concatenated array
    // The factory takes the array pointer directly
    const new_string_ptr = zeus_new_string(new_array_ptr);

    // Write result pointer using Zeus return wrapper ABI
    // The wrapper is a struct with [header_ptr, result_value]
    if (runtime_util.allocateReturnBuffer(return_buffer_ptr_ptr, @sizeOf(*anyopaque))) |result_bytes| {
        const result_ptr = @as(**anyopaque, @ptrCast(@alignCast(result_bytes.ptr)));
        result_ptr.* = new_string_ptr;
    }
}
