// Zeus String Runtime Functions
// String primordial runtime functions for Zeus strings

const std = @import("std");
const abi = @import("abi.zig");
const runtime_util = @import("runtime_util.zig");

// ============================================================================
// String Object ABI
// ============================================================================

/// Zeus string object layout
/// Matches the LLVM struct generated by codegen for the string class
pub const ZeusStringObj = extern struct {
    obj_header: *abi.ZeusObjectHeader,
    data: ?*abi.ZeusArrayObj, // The u8[] array containing the string bytes
};

/// Safely cast anyopaque pointer to ZeusStringObj pointer
pub inline fn castToStringObj(ptr: *anyopaque) *ZeusStringObj {
    return @as(*ZeusStringObj, @ptrCast(@alignCast(ptr)));
}

// ============================================================================
// Exported Runtime Functions
// ============================================================================

/// Constructor: zeus_string_constructor(this_ptr, return_buffer, bytes_ptr_ptr)
/// Creates a string object from a u8[] array
/// NOTE: bytes_ptr_ptr is a pointer to the array pointer (passed via alloca from wrapper)
export fn zeus_string_constructor(this_ptr: *anyopaque, return_buffer_ptr: ?*anyopaque, bytes_ptr_ptr: *anyopaque) callconv(.C) void {
    _ = return_buffer_ptr; // void return, not used

    const string_ptr = castToStringObj(this_ptr);

    // Dereference to get the actual ZeusArrayObj pointer
    const array_obj_ptr = @as(**anyopaque, @ptrCast(@alignCast(bytes_ptr_ptr))).*;
    const array_ptr = runtime_util.castToArrayObj(array_obj_ptr);

    // Store the u8[] reference directly in the string's data field
    string_ptr.data = array_ptr;
}

/// Get the length of a string (number of bytes)
export fn zeus_string_length(string_ptr: *anyopaque, return_buffer_ptr: ?*anyopaque) callconv(.C) void {
    const str = castToStringObj(string_ptr);

    var length: u32 = 0;
    if (str.data) |array| {
        length = array.length;
    }

    // Write length to return buffer
    if (return_buffer_ptr) |ret_ptr| {
        const result_ptr = @as(*u32, @ptrCast(@alignCast(ret_ptr)));
        result_ptr.* = length;
    }
}
