package ir

import (
	"fmt"
	"strings"

	"github.com/ameerthehacker/zeus/internal/token"
	"github.com/ameerthehacker/zeus/internal/zeus_error"
	"github.com/ameerthehacker/zeus/internal/zeus_value"
)

// TCPass represents a pluggable pass that can be run on the IR
// Passes receive individual instructions with automatic context management
type TCPass interface {
	// HandleInstruction processes a single instruction
	// The TypeChecker automatically manages currentFunction, currentClass, and currentBlock
	HandleInstruction(tc *TypeChecker, instr *Instr)

	// Finalize is called after all instructions have been processed
	// This allows passes to perform cleanup or final analysis
	Finalize(tc *TypeChecker)

	// GetName returns the name of the pass for debugging/logging
	GetName() string
}

type TypeChecker struct {
	errors          []*zeus_error.ZeusError
	currentFunction *zeus_value.Function
	currentClass    *zeus_value.Class
	builder         *IRBuilder
	currentBlock    *BasicBlock
	passes          []TCPass
	IsEntryPoint    bool
}

func NewTypeChecker(builder *IRBuilder, isEntryPoint bool) *TypeChecker {
	tc := &TypeChecker{
		builder:      builder,
		IsEntryPoint: isEntryPoint,
	}

	// Initialize required passes
	tc.passes = []TCPass{
		NewPrimordialClassGenPass(),
		NewToKnownTypesPass(),
		NewTypeCheckingPass(),
		NewUnusedWarningPass(),
	}

	return tc
}

// AddPass adds a new pass to the type checker
func (tc *TypeChecker) AddPass(pass TCPass) {
	tc.passes = append(tc.passes, pass)
}

// TypeCheck runs all registered passes and returns accumulated errors
func (tc *TypeChecker) TypeCheck() []*zeus_error.ZeusError {
	tc.errors = nil // Reset errors

	for _, pass := range tc.passes {
		tc.runPass(pass)
	}

	return tc.errors
}

// runPass executes a single pass with automatic context management
func (tc *TypeChecker) runPass(pass TCPass) {
	tc.builder.Walk(func(instr *Instr) {
		// Automatically update context based on instruction type
		tc.updateContext(instr)

		// Check if instruction is allowed in current context
		if !tc.isInstructionAllowed(instr) {
			tc.pushError(&zeus_error.ZeusError{
				Message: "statement not supported outside of function",
				Span:    instr.Span,
			})
			return
		}

		// Let the pass handle the instruction
		pass.HandleInstruction(tc, instr)
	}, func(block *BasicBlock) {
		tc.currentBlock = block
	})

	// Call finalize after processing all instructions
	pass.Finalize(tc)
}

// updateContext automatically updates the current function and class context
func (tc *TypeChecker) updateContext(instr *Instr) {
	switch instr.Type {
	case InstrTypeDeclFunc:
		input := AsDeclFuncInstrInput(instr.Input)
		tc.currentFunction = input.Function
	case InstrTypeDeclClassMethod:
		input := AsDeclClassMethodInstrInput(instr.Input)
		tc.currentClass = input.Class
		tc.currentFunction = input.Method
	case InstrTypeDeclClass:
		input := AsDeclClassInstrInput(instr.Input)
		tc.currentClass = input.Class
	}
}

// isInstructionAllowed checks if an instruction is allowed in the current context
func (tc *TypeChecker) isInstructionAllowed(instr *Instr) bool {
	isTopLevelInstr := IsFunctionDeclInstr(instr.Type) || IsClassDeclInstr(instr.Type) || IsClassMethodDeclInstr(instr.Type) || IsExportInstr(instr.Type) || IsImportInstr(instr.Type) || IsPrimordialFunctionDeclInstr(instr.Type)
	return isTopLevelInstr || tc.currentFunction != nil
}

// Common utility functions shared by all passes

// getBuiltInValueType returns the built-in value type of a value
func (tc *TypeChecker) getBuiltInValueType(value zeus_value.Value) zeus_value.ValueType {
	switch value := value.(type) {
	case *zeus_value.Var:
		return value.ValueType
	case *zeus_value.Function:
		return zeus_value.ToFunctionType(*value)
	case *zeus_value.Constant:
		return value.ValueType
	case *zeus_value.Object:
		return value.ValueType
	case *zeus_value.Class:
		return zeus_value.NewObjectType(*value)
	default:
		if value == nil {
			return zeus_value.UndefinedType{}
		}
		return zeus_value.UndefinedType{Span: value.GetSpan()}
	}
}

// getValueType returns the value type of a value
func (tc *TypeChecker) getValueType(value zeus_value.Value) zeus_value.ValueType {
	if value == nil {
		return zeus_value.UndefinedType{}
	}

	valueType := tc.getBuiltInValueType(value)

	if valueType == nil {
		return zeus_value.UndefinedType{Span: value.GetSpan()}
	}

	return valueType
}

func (tc *TypeChecker) pushError(err *zeus_error.ZeusError) {
	tc.errors = append(tc.errors, err)
}

// getClassFromArrayType extracts a class from either an ObjectType or ArrayType
// For ObjectType, it returns the class directly
// For ArrayType, it looks up the array primordial class from the symbol table
// Note: Array class definitions are now pre-generated by PrimordialClassGenPass
func (tc *TypeChecker) getClassFromArrayType(arrayType zeus_value.ArrayType) *zeus_value.Class {
	arrayTypeClassName := arrayType.String()
	
	// Try to get existing class from symbol table
	if class, ok := tc.builder.symbolTable.GetSymbol(arrayTypeClassName); ok {
		classValue, ok := class.(*zeus_value.Class)
		zeus_error.Assert(ok, fmt.Sprintf("array element type %s is not a class", arrayTypeClassName))
		return classValue
	}
	
	// This should never happen - PrimordialClassGenPass should have already created this class
	zeus_error.Assert(false, fmt.Sprintf("PrimordialClassGenPass did not create class for array type %s", arrayTypeClassName))
	return nil
}

// PrimordialClassGenPass collects all array types and user-defined types that match primordial class names
// and generates class declarations for them at the top level
type PrimordialClassGenPass struct {
	arrayTypes      map[string]zeus_value.ArrayType
	primordialTypes map[string]*token.Span // tracks user-defined types matching primordial names
}

func NewPrimordialClassGenPass() *PrimordialClassGenPass {
	return &PrimordialClassGenPass{
		arrayTypes:      make(map[string]zeus_value.ArrayType),
		primordialTypes: make(map[string]*token.Span),
	}
}

func (p *PrimordialClassGenPass) GetName() string {
	return "PrimordialClassGenPass"
}

func (p *PrimordialClassGenPass) HandleInstruction(tc *TypeChecker, instr *Instr) {
	// Collect types from instruction outputs
	if instr.Output != nil && instr.Output.ValueType != nil {
		p.collectType(instr.Output.ValueType)
	}

	// Collect from specific instruction types
	switch instr.Type {
	case InstrTypeDeclVar:
		input := AsDeclVarInstrInput(instr.Input)
		p.collectType(input.Variable.ValueType)
	case InstrTypeDeclFunc:
		input := AsDeclFuncInstrInput(instr.Input)
		p.collectType(input.Function.ReturnType)
		for _, param := range input.Function.Params {
			p.collectType(param.ValueType)
		}
	case InstrTypeDeclPrimordialFunc:
		input := AsDeclPrimordialFuncInstrInput(instr.Input)
		p.collectType(input.Function.ReturnType)
		for _, param := range input.Function.Params {
			p.collectType(param.ValueType)
		}
	case InstrTypeDeclClass:
		input := AsDeclClassInstrInput(instr.Input)
		for _, property := range input.Class.Properties {
			p.collectType(property.Property.ValueType)
		}
		if input.Class.ArrayElementType != nil {
			p.collectType(input.Class.ArrayElementType)
		}
	case InstrTypeDeclClassMethod:
		input := AsDeclClassMethodInstrInput(instr.Input)
		p.collectType(input.Method.ReturnType)
		for _, param := range input.Method.Params {
			p.collectType(param.ValueType)
		}
	}
}

func (p *PrimordialClassGenPass) collectType(valueType zeus_value.ValueType) {
	if zeus_value.IsArrayType(valueType) {
		p.collectArrayType(valueType)
	} else if zeus_value.IsUserDefinedType(valueType) {
		p.collectUserDefinedType(valueType)
	}
}

func (p *PrimordialClassGenPass) collectUserDefinedType(valueType zeus_value.ValueType) {
	userDefinedType := zeus_value.AsUserDefinedType(valueType)
	// Check if this is a known primordial class name
	if p.isPrimordialClassName(userDefinedType.Name) {
		if _, exists := p.primordialTypes[userDefinedType.Name]; !exists {
			p.primordialTypes[userDefinedType.Name] = userDefinedType.Span
		}
	}
}

func (p *PrimordialClassGenPass) isPrimordialClassName(name string) bool {
	return name == zeus_value.ZEUS_PRIMORDIAL_STRING
}

func (p *PrimordialClassGenPass) collectArrayType(valueType zeus_value.ValueType) {
	if zeus_value.IsArrayType(valueType) {
		arrayType := zeus_value.AsArrayType(valueType)
		typeName := arrayType.String()
		
		// Only add if not already collected
		if _, exists := p.arrayTypes[typeName]; !exists {
			p.arrayTypes[typeName] = *arrayType
		}
		
		// Recursively collect element types if they are also arrays or user-defined types
		p.collectType(arrayType.ElementType)
	}
}

// emittedClasses tracks which primordial classes have been emitted to avoid duplicates
var emittedClasses = make(map[string]bool)

// primordialInsertionIndex tracks where to insert the next primordial class declaration
// This ensures dependencies are emitted in the correct order (dependencies first)
var primordialInsertionIndex = 0

func (p *PrimordialClassGenPass) Finalize(tc *TypeChecker) {
	// Reset trackers
	emittedClasses = make(map[string]bool)
	primordialInsertionIndex = 0
	
	// Generate class declarations for all collected array types first
	// We need to sort them by depth (simpler types first) to ensure dependencies are resolved
	sortedTypes := p.sortArrayTypesByDepth()
	
	for _, arrayType := range sortedTypes {
		p.emitArrayClass(tc, arrayType)
	}
	
	// Emit DECL_CLASS instructions for primordial types that are used (like "string")
	for typeName, span := range p.primordialTypes {
		p.emitPrimordialClass(tc, typeName, span)
	}
}

// emitArrayClass emits a DECL_CLASS instruction for an array type if not already emitted
func (p *PrimordialClassGenPass) emitArrayClass(tc *TypeChecker, arrayType zeus_value.ArrayType) {
	typeName := arrayType.String()
	
	// Skip if already emitted
	if emittedClasses[typeName] {
		return
	}
	
	// Check if class already exists in symbol table (might be pre-registered)
	var arrayClass *zeus_value.Class
	if symbol, ok := tc.builder.symbolTable.GetSymbol(typeName); ok {
		arrayClass = zeus_value.AsClass(symbol)
	} else {
		// Create and register the array primordial class
		arrayClass = zeus_value.GetArrayPrimordialClassDefinition(arrayType)
		tc.builder.symbolTable.DeclareSymbol(typeName, arrayClass)
	}
	
	if arrayClass == nil {
		return
	}
	
	// Mark as emitted before emitting to handle circular dependencies
	emittedClasses[typeName] = true
	
	// Emit DECL_CLASS instruction at the current insertion index
	// This ensures proper ordering: dependencies come before dependents
	result := tc.builder.createTempVariable(arrayType.GetSpan())
	tc.builder.insertionIndex = primordialInsertionIndex
	tc.builder.currentBlock = nil
	tc.builder.pushInstr(&Instr{
		Type:   InstrTypeDeclClass,
		Output: result,
		Input:  NewDeclClassInstrInput(arrayClass),
		Span:   arrayType.GetSpan(),
	})
	primordialInsertionIndex++
}

// emitPrimordialClass emits a DECL_CLASS instruction for a primordial class and its dependencies
func (p *PrimordialClassGenPass) emitPrimordialClass(tc *TypeChecker, typeName string, span *token.Span) {
	// Skip if already emitted
	if emittedClasses[typeName] {
		return
	}
	
	// Get the primordial class from symbol table (already registered in ir.go)
	symbol, ok := tc.builder.symbolTable.GetSymbol(typeName)
	if !ok {
		return
	}
	
	primordialClass := zeus_value.AsClass(symbol)
	if primordialClass == nil {
		return
	}
	
	// Handle transitive dependencies: emit dependent primordial classes first
	for _, property := range primordialClass.Properties {
		if zeus_value.IsObjectType(property.Property.ValueType) {
			objType := zeus_value.AsObjectType(property.Property.ValueType)
			if objType.Class.PrimordialName == zeus_value.ZEUS_PRIMORDIAL_ARRAY {
				// This is an array dependency, emit it first
				// Reconstruct the array type from the class
				if objType.Class.ArrayElementType != nil {
					depArrayType := zeus_value.ArrayType{
						ElementType: objType.Class.ArrayElementType,
						Span:        span,
					}
					p.emitArrayClass(tc, depArrayType)
				}
			} else if objType.Class.PrimordialName != "" {
				// This is another primordial class dependency
				p.emitPrimordialClass(tc, objType.Class.Name, span)
			}
		}
	}
	
	// Mark as emitted
	emittedClasses[typeName] = true
	
	// Emit DECL_CLASS instruction at the current insertion index
	result := tc.builder.createTempVariable(span)
	tc.builder.insertionIndex = primordialInsertionIndex
	tc.builder.currentBlock = nil
	tc.builder.pushInstr(&Instr{
		Type:   InstrTypeDeclClass,
		Output: result,
		Input:  NewDeclClassInstrInput(primordialClass),
		Span:   span,
	})
	primordialInsertionIndex++
}

// sortArrayTypesByDepth sorts array types so that simpler types (fewer dimensions) come first
func (p *PrimordialClassGenPass) sortArrayTypesByDepth() []zeus_value.ArrayType {
	var result []zeus_value.ArrayType
	
	// Calculate depth for each type
	type typeWithDepth struct {
		arrayType zeus_value.ArrayType
		depth     int
	}
	
	var typesWithDepth []typeWithDepth
	for _, arrayType := range p.arrayTypes {
		depth := p.calculateDepth(arrayType)
		typesWithDepth = append(typesWithDepth, typeWithDepth{arrayType, depth})
	}
	
	// Sort by depth (ascending)
	for i := 0; i < len(typesWithDepth); i++ {
		for j := i + 1; j < len(typesWithDepth); j++ {
			if typesWithDepth[i].depth > typesWithDepth[j].depth {
				typesWithDepth[i], typesWithDepth[j] = typesWithDepth[j], typesWithDepth[i]
			}
		}
	}
	
	for _, td := range typesWithDepth {
		result = append(result, td.arrayType)
	}
	
	return result
}

func (p *PrimordialClassGenPass) calculateDepth(arrayType zeus_value.ArrayType) int {
	depth := 1
	currentType := arrayType.ElementType
	
	for {
		if at, ok := currentType.(zeus_value.ArrayType); ok {
			depth++
			currentType = at.ElementType
		} else {
			break
		}
	}
	
	return depth
}

// ToKnownTypesPass converts all UserDefinedType references to their actual known types
type ToKnownTypesPass struct{}

func NewToKnownTypesPass() *ToKnownTypesPass {
	return &ToKnownTypesPass{}
}

func (p *ToKnownTypesPass) GetName() string {
	return "ToKnownTypesPass"
}

func (p *ToKnownTypesPass) Finalize(tc *TypeChecker) {
	// No finalization needed for this pass
}

func (p *ToKnownTypesPass) HandleInstruction(tc *TypeChecker, instr *Instr) {
	// Resolve output type if it exists and is a UserDefinedType
	if instr.Output != nil && instr.Output.ValueType != nil {
		instr.Output.ValueType = p.resolveValueType(tc, instr.Output.ValueType, true)
	}

	switch instr.Type {
	case InstrTypeDeclVar:
		p.resolveVarDecl(tc, instr)
	case InstrTypeDeclFunc:
		p.resolveFuncDecl(tc, instr)
	case InstrTypeDeclPrimordialFunc:
		p.resolvePrimordialFuncDecl(tc, instr)
	case InstrTypeDeclClass:
		p.resolveClassDecl(tc, instr)
	case InstrTypeDeclClassMethod:
		p.resolveClassMethodDecl(tc, instr)
	}
}

// resolveValueType converts a UserDefinedType to its actual known type
func (p *ToKnownTypesPass) resolveValueType(tc *TypeChecker, valueType zeus_value.ValueType, isReturnType bool) zeus_value.ValueType {
	undefinedType := zeus_value.UndefinedType{Span: valueType.GetSpan()}
	if zeus_value.IsUserDefinedType(valueType) {
		userDefinedType := zeus_value.AsUserDefinedType(valueType)
		variable, ok := tc.builder.symbolTable.GetSymbol(userDefinedType.Name)

		if !ok {
			// Return undefined type if we can't resolve it
			// The TypeCheckingPass will handle the error
			tc.pushError(&zeus_error.ZeusError{
				Message: fmt.Sprintf("unknown type '%s'", userDefinedType.Name),
				Span:    valueType.GetSpan(),
			})
			return undefinedType
		}

		return tc.getBuiltInValueType(variable)
	} else if zeus_value.IsArrayType(valueType) {
		// we convert all the array types to objects
		arrayType := zeus_value.AsArrayType(valueType)
		resolvedElementType := p.resolveValueType(tc, arrayType.ElementType, false)
		
		// If element type resolution failed, return undefined type
		if zeus_value.IsUndefinedType(resolvedElementType) {
			return undefinedType
		}
		
		arrayType.ElementType = resolvedElementType
		class := tc.getClassFromArrayType(*arrayType)
		return zeus_value.NewObjectType(*class)
	} else if zeus_value.IsNullType(valueType) {
		tc.pushError(&zeus_error.ZeusError{
			Message: "cannot use null as a standalone type",
			Span:    valueType.GetSpan(),
		})
		return undefinedType
	} else if !isReturnType && zeus_value.IsVoidType(valueType) {
		tc.pushError(&zeus_error.ZeusError{
			Message: "void type can be used only as a return type",
			Span:    valueType.GetSpan(),
		})
		return undefinedType
	}

	return valueType
}

func (p *ToKnownTypesPass) resolveVarDecl(tc *TypeChecker, instr *Instr) {
	input := AsDeclVarInstrInput(instr.Input)
	if input.Variable.ValueType == nil {
		// Type will be inferred from stores (e.g. ternary result variable).
		return
	}
	input.Variable.ValueType = p.resolveValueType(tc, input.Variable.ValueType, false)
}

func (p *ToKnownTypesPass) resolveFuncDecl(tc *TypeChecker, instr *Instr) {
	input := AsDeclFuncInstrInput(instr.Input)

	// Resolve return type
	input.Function.ReturnType = p.resolveValueType(tc, input.Function.ReturnType, true)

	// Resolve parameter types
	for i := range input.Function.Params {
		input.Function.Params[i].ValueType = p.resolveValueType(tc, input.Function.Params[i].ValueType, false)
	}
}

func (p *ToKnownTypesPass) resolvePrimordialFuncDecl(tc *TypeChecker, instr *Instr) {
	input := AsDeclPrimordialFuncInstrInput(instr.Input)
	input.Function.ReturnType = p.resolveValueType(tc, input.Function.ReturnType, true)
	for i := range input.Function.Params {
		input.Function.Params[i].ValueType = p.resolveValueType(tc, input.Function.Params[i].ValueType, false)
	}
}

func (p* ToKnownTypesPass) resolveClass(tc *TypeChecker, class *zeus_value.Class) *zeus_value.Class {
	// Resolve property types
	for i := range class.Properties {
		class.Properties[i].Property.ValueType = p.resolveValueType(tc, class.Properties[i].Property.ValueType, false)
	}

	if class.ArrayElementType != nil {
		class.ArrayElementType = p.resolveValueType(tc, class.ArrayElementType, false)
	}

	// Resolve method types
	for i := range class.Methods {
		method := class.Methods[i].Method
		method.ReturnType = p.resolveValueType(tc, method.ReturnType, true)

		for j := range method.Params {
			method.Params[j].ValueType = p.resolveValueType(tc, method.Params[j].ValueType, false)
		}
	}

	return class
}

func (p *ToKnownTypesPass) resolveClassDecl(tc *TypeChecker, instr *Instr) {
	input := AsDeclClassInstrInput(instr.Input)

	p.resolveClass(tc, input.Class)
}

func (p *ToKnownTypesPass) resolveClassMethodDecl(tc *TypeChecker, instr *Instr) {
	input := AsDeclClassMethodInstrInput(instr.Input)

	// Resolve return type
	input.Method.ReturnType = p.resolveValueType(tc, input.Method.ReturnType, true)

	// Resolve parameter types
	for i := range input.Method.Params {
		input.Method.Params[i].ValueType = p.resolveValueType(tc, input.Method.Params[i].ValueType, false)
	}
}

// This pass does the actual type checking
type TypeCheckingPass struct {
	hasMainFunction bool
	firstUserSpan   *token.Span
}

func NewTypeCheckingPass() *TypeCheckingPass {
	return &TypeCheckingPass{
		hasMainFunction: false,
	}
}

func (p *TypeCheckingPass) GetName() string {
	return "TypeCheckingPass"
}

func (p *TypeCheckingPass) Finalize(tc *TypeChecker) {
	if !p.hasMainFunction && tc.IsEntryPoint {
		tc.pushError(&zeus_error.ZeusError{
			Message: "main function not found",
			Span:    p.firstUserSpan,
		})
	}
}

func (p *TypeCheckingPass) HandleInstruction(tc *TypeChecker, instr *Instr) {
	// Track the first span from user-written code (skip primordial declarations)
	if p.firstUserSpan == nil && instr.Span != nil && instr.Type != InstrTypeDeclPrimordialFunc {
		p.firstUserSpan = instr.Span
	}

	switch instr.Type {
	// jmp requires no type checking
	case InstrTypeJmp:
	case InstrTypeDeclFunc:
		p.tcFuncDecl(tc, instr)
	case InstrTypeDeclVar:
		p.tcDeclVar(tc, instr)
	case InstrTypeAdd:
		p.tcBinaryOp(tc, instr, func(a, b zeus_value.ValueType) zeus_value.ValueType {
			// String + string returns string
			if isStringType(a) && isStringType(b) {
				return a
			}
			return zeus_value.GetBiggerType(a, b)
		}, func(a, b zeus_value.ValueType) bool {
			// Allow number + number
			if zeus_value.IsNumberType(a) && zeus_value.IsNumberType(b) {
				return true
			}
			// Allow string + string (concatenation)
			if isStringType(a) && isStringType(b) {
				return true
			}
			return false
		})
	case InstrTypeSub:
		fallthrough
	case InstrTypeMul:
		fallthrough
	case InstrTypeDiv:
		p.tcBinaryOp(tc, instr, zeus_value.GetBiggerType, func(a, b zeus_value.ValueType) bool {
			return zeus_value.IsNumberType(a) && zeus_value.IsNumberType(b)
		})
	case InstrTypeMod:
		// Modulo only works on integers
		p.tcBinaryOp(tc, instr, zeus_value.GetBiggerType, func(a, b zeus_value.ValueType) bool {
			return zeus_value.IsIntType(a) && zeus_value.IsIntType(b)
		})
	case InstrTypePower:
		// Power works on numeric types (result is float if either operand is float)
		p.tcBinaryOp(tc, instr, func(a, b zeus_value.ValueType) zeus_value.ValueType {
			// If either is a float, result is float
			if zeus_value.IsFloatType(a) || zeus_value.IsFloatType(b) {
				return zeus_value.GetBiggerType(a, b)
			}
			// Integer power: for now, return the type of the base
			// In practice, we might want to promote to f64 for safety
			return a
		}, func(a, b zeus_value.ValueType) bool {
			return zeus_value.IsNumberType(a) && zeus_value.IsNumberType(b)
		})
	case InstrTypeEqEq:
		fallthrough
	case InstrTypeNotEq:
		p.tcBinaryOp(tc, instr, func(_, _ zeus_value.ValueType) zeus_value.ValueType {
			return zeus_value.BoolType{}
		}, func(a, b zeus_value.ValueType) bool {
			// Allow number comparisons
			if zeus_value.IsNumberType(a) && zeus_value.IsNumberType(b) {
				return true
			}
			// Allow object type (class instances) compared with null
			if zeus_value.IsObjectType(a) && zeus_value.IsNullType(b) {
				return true
			}
			if zeus_value.IsNullType(a) && zeus_value.IsObjectType(b) {
				return true
			}
			// Allow two object types to be compared
			if zeus_value.IsObjectType(a) && zeus_value.IsObjectType(b) {
				return true
			}
			// Allow boolean comparisons
			if zeus_value.IsBoolType(a) && zeus_value.IsBoolType(b) {
				return true
			}
			// Allow string comparisons
			if isStringType(a) && isStringType(b) {
				return true
			}
			return false
		})
	case InstrTypeLessThan:
		fallthrough
	case InstrTypeGreaterThan:
		fallthrough
	case InstrTypeLessThanEq:
		fallthrough
	case InstrTypeGreaterThanEq:
		p.tcBinaryOp(tc, instr, func(_, _ zeus_value.ValueType) zeus_value.ValueType {
			return zeus_value.BoolType{}
		}, func(a, b zeus_value.ValueType) bool {
			// Allow number comparisons
			if zeus_value.IsNumberType(a) && zeus_value.IsNumberType(b) {
				return true
			}
			// Allow string comparisons
			if isStringType(a) && isStringType(b) {
				return true
			}
			return false
		})
	case InstrTypeNot:
		p.tcUnaryOp(tc, instr, func(_ zeus_value.ValueType) zeus_value.ValueType {
			return zeus_value.BoolType{}
		}, zeus_value.IsBoolType)
	case InstrTypeAnd:
		fallthrough
	case InstrTypeOr:
		// Logical AND/OR: both operands must be bool, result is bool
		p.tcBinaryOp(tc, instr, func(_, _ zeus_value.ValueType) zeus_value.ValueType {
			return zeus_value.BoolType{}
		}, func(a, b zeus_value.ValueType) bool {
			return zeus_value.IsBoolType(a) && zeus_value.IsBoolType(b)
		})
	case InstrTypeBitAnd:
		fallthrough
	case InstrTypeBitOr:
		fallthrough
	case InstrTypeBitXor:
		fallthrough
	case InstrTypeShl:
		fallthrough
	case InstrTypeShr:
		// Bitwise ops: both operands must be integers, result is the bigger int type
		p.tcBinaryOp(tc, instr, zeus_value.GetBiggerType, func(a, b zeus_value.ValueType) bool {
			return zeus_value.IsIntType(a) && zeus_value.IsIntType(b)
		})
	case InstrTypeBitNot:
		// Bitwise NOT: operand must be integer, result is same type
		p.tcUnaryOp(tc, instr, func(operandType zeus_value.ValueType) zeus_value.ValueType {
			return operandType
		}, zeus_value.IsIntType)
	case InstrTypeNeg:
		p.tcUnaryOp(tc, instr, func(operandType zeus_value.ValueType) zeus_value.ValueType {
			switch operandType := operandType.(type) {
			// negation on int makes it signed
			case zeus_value.IntType:
				return zeus_value.IntType{
					Signed: true,
					Size:   operandType.Size,
				}
			}
			return operandType
		}, zeus_value.IsNumberType)
	case InstrTypeCondJmp:
		p.tcCondJmp(tc, instr)
	case InstrTypeLoad:
		p.tcLoad(instr)
	case InstrTypeStore:
		p.tcStore(tc, instr)
	case InstrTypeReturn:
		p.tcReturn(tc, instr)
	case InstrTypeCallFunc:
		p.tcCallFunc(tc, instr)
	case InstrTypeIndirectFuncCall:
		p.tcIndirectFuncCall(tc, instr)
	case InstrTypeExport:
		p.tcExport(tc, instr)
	case InstrTypeImport:
		p.tcImport(tc, instr)
	case InstrTypeDeclClass:
		p.tcDeclClass(tc, instr)
	case InstrTypeNewObj:
		p.tcNewObj(tc, instr)
	case InstrTypeObjectPropertyAccess:
		p.tcObjectPropertyAccess(tc, instr)
	case InstrTypeDeclClassMethod:
		p.tcDeclClassMethod(tc, instr)
	case InstrTypeCast:
		// TODO: add type checking for cast
	case InstrTypeDeclPrimordialFunc:
		// no type checking for primordial functions
	case InstrTypeGetIndex:
		p.tcGetIndex(tc, instr)
	// Exception handling instructions
	case InstrTypeThrow:
		p.tcThrow(tc, instr)
	case InstrTypePushHandler:
		// Push handler doesn't require type checking
	case InstrTypePopHandler:
		// Pop handler doesn't require type checking
	case InstrTypeCheckException:
		// Check exception doesn't require type checking
	case InstrTypeGetException:
		// Get exception sets output type to the exception pointer type
		// This will be resolved when binding to catch variable
	case InstrTypeClearException:
		// Clear exception doesn't require type checking
	default:
		panic(fmt.Sprintf("type checking not handled for instruction: %s", instr.Type))
	}
}

// validateFunctionReturns checks if a function returns in all code paths
func (p *TypeCheckingPass) validateFunctionReturns(tc *TypeChecker, function *zeus_value.Function, functionBody *BasicBlock) {
	returnsInAllBlocks := true
	worklist := []*BasicBlock{functionBody}

	for len(worklist) > 0 {
		block := worklist[0]

		if len(block.Instrs) == 0 || !IsControlFlowInstr(block.Instrs[len(block.Instrs)-1].Type) {
			// add implicit return
			if zeus_value.IsVoidType(function.ReturnType) {
				tc.builder.SetInsertionBlock(block)
				tc.builder.BuildReturn(nil, nil)
			} else {
				returnsInAllBlocks = false
			}
		}

		worklist = worklist[1:]
		worklist = append(worklist, block.Successors...)
	}

	if !returnsInAllBlocks {
		tc.pushError(&zeus_error.ZeusError{
			Message: fmt.Sprintf("function '%s' does not return value of type '%s' in all paths", function.Name, function.ReturnType),
			Span:    function.Span,
		})
	}
}

func (p *TypeCheckingPass) tcFuncDecl(tc *TypeChecker, instr *Instr) {
	input := AsDeclFuncInstrInput(instr.Input)

	if input.Function.Name == token.MAIN_FUNCTION_NAME && tc.IsEntryPoint {
		p.hasMainFunction = true
	}

	p.validateFunctionReturns(tc, input.Function, input.Body)
}

func (p *TypeCheckingPass) tcDeclVar(tc *TypeChecker, instr *Instr) {
	decl_var := AsDeclVarInstrInput(instr.Input)

	if zeus_value.IsVoidType(decl_var.Variable.ValueType) {
		tc.pushError(&zeus_error.ZeusError{
			Message: fmt.Sprintf("cannot declare variable of type '%s'", decl_var.Variable.ValueType),
			Span:    decl_var.Variable.Span,
		})
	} else if decl_var.Initializer != nil {
		initializer := p.cmpValueWithImplicitCast(tc, instr, decl_var.Variable.ValueType, decl_var.Initializer)
		decl_var.Initializer = initializer
	}
}

func (p *TypeCheckingPass) cmpValueWithImplicitCast(tc *TypeChecker, instr *Instr, targetType zeus_value.ValueType, b zeus_value.Value) zeus_value.Value {
	bType := tc.getValueType(b)

	if !zeus_value.CmpValueType(targetType, bType) {
		castedB, ok := p.tryImplicitCast(tc, instr, b, targetType)

		if ok {
			return castedB
		} else {
			if bType == nil {
				bType = zeus_value.UndefinedType{Span: b.GetSpan()}
			}
			if targetType == nil {
				targetType = zeus_value.UndefinedType{Span: b.GetSpan()}
			}
			tc.pushError(&zeus_error.ZeusError{
				Message: fmt.Sprintf("type '%s' is not assignable to type '%s'", bType.String(), targetType.String()),
				Span:    instr.Span,
			})
		}
	}

	return b
}

// Performs the following implicit casts:
// - int to float
// - int to int of bigger size
// - float to float of bigger size
func (p *TypeCheckingPass) tryImplicitCast(tc *TypeChecker, instr *Instr, value zeus_value.Value, targetType zeus_value.ValueType) (zeus_value.Value, bool) {
	valueType := tc.getValueType(value)

	// if they both are same type, no need to cast
	if zeus_value.CmpValueType(valueType, targetType) {
		return value, true
	}

	zeus_error.Assert(tc.currentBlock != nil, "current block is nil")
	tc.builder.SetBlockInsertionBefore(tc.currentBlock, instr)

	castIntToFloat := func(intType zeus_value.IntType, value zeus_value.Value) zeus_value.Value {
		size := zeus_value.F32
		if intType.Size == zeus_value.I64 {
			size = zeus_value.F64
		}

		return tc.builder.BuildCast(value, zeus_value.FloatType{Size: size}, value.GetSpan())
	}

	switch valueType := valueType.(type) {
	case zeus_value.IntType:
		switch targetType := targetType.(type) {
		case zeus_value.IntType:
			// value and target are signed and the target is larger
			canFitValue := targetType.Size > valueType.Size && valueType.Signed == targetType.Signed
			// value is unsigned and target is signed and the target is larger
			canFitUnsigned := targetType.Signed && !valueType.Signed && targetType.Size > valueType.Size
			// value is a constant and the target is larger
			constant := zeus_value.AsConstant(value)
			canFitUnsignedConstant := constant != nil && targetType.Size >= zeus_value.GetSignedIntSize(constant.Value)

			if canFitValue || canFitUnsigned || canFitUnsignedConstant {
				return tc.builder.BuildCast(value, targetType, value.GetSpan()), true
			}
		case zeus_value.FloatType:
			return castIntToFloat(valueType, value), true
		}
	case zeus_value.FloatType:
		switch targetType := targetType.(type) {
		case zeus_value.FloatType:
			if targetType.Size > valueType.Size {
				return tc.builder.BuildCast(value, targetType, value.GetSpan()), true
			}
		}
	case zeus_value.ArrayType:
		switch targetType := targetType.(type) {
		case zeus_value.ObjectType:
			// if the class name is stringifies version of value type, then it is a valid cast
			// This handles u8[] -> u8[] (as ObjectType) which is a no-op cast
			if targetType.Class.Name == valueType.String() {
				return value, true
			}
			// u8[] -> string implicit cast: emit CAST instruction (lowered in separate pass)
			if isU8ArrayType(valueType) && targetType.Class.Name == zeus_value.ZEUS_PRIMORDIAL_STRING {
				return tc.builder.BuildCast(value, targetType, value.GetSpan()), true
			}
		}
	case zeus_value.ObjectType:
		switch targetType := targetType.(type) {
		case zeus_value.ArrayType:
			// if the class name is stringifies version of value type, then it is a valid cast
			if valueType.Class.Name == targetType.String() {
				return value, true
			}
			// string -> u8[] implicit cast: emit CAST instruction (lowered in separate pass)
			if valueType.Class.Name == zeus_value.ZEUS_PRIMORDIAL_STRING && isU8ArrayType(targetType) {
				return tc.builder.BuildCast(value, targetType, value.GetSpan()), true
			}
		case zeus_value.ObjectType:
			// Handle ObjectType -> ObjectType casts (after ToKnownTypesPass converts ArrayType to ObjectType)
			// string -> u8[] (as ObjectType) implicit cast: emit CAST instruction (lowered in separate pass)
			if valueType.Class.Name == zeus_value.ZEUS_PRIMORDIAL_STRING && targetType.Class.Name == "u8[]" {
				u8ArrayType := zeus_value.ArrayType{
					ElementType: zeus_value.IntType{Size: zeus_value.I8, Signed: false, Span: value.GetSpan()},
					Span:        value.GetSpan(),
				}
				return tc.builder.BuildCast(value, u8ArrayType, value.GetSpan()), true
			}
			// u8[] (as ObjectType) -> string implicit cast: emit CAST instruction (lowered in separate pass)
			if valueType.Class.Name == "u8[]" && targetType.Class.Name == zeus_value.ZEUS_PRIMORDIAL_STRING {
				return tc.builder.BuildCast(value, targetType, value.GetSpan()), true
			}
		}
	case zeus_value.NullType:
		switch targetType := targetType.(type) {
		case zeus_value.ObjectType:
			// Promote the null constant to the target object type so the codegen
			// can emit a ConstPointerNull of the correct address-space pointer type.
			return zeus_value.NewConstant(zeus_value.NULL_CONSTANT_VALUE, targetType, value.GetSpan()), true
		}
	}

	return value, false
}

// isU8ArrayType checks if a type is u8[] (array of unsigned 8-bit integers)
// isStringType checks if a type is a string type
func isStringType(valueType zeus_value.ValueType) bool {
	if objType, ok := valueType.(zeus_value.ObjectType); ok {
		return objType.Class.Name == zeus_value.ZEUS_PRIMORDIAL_STRING
	}
	return false
}

func isU8ArrayType(valueType zeus_value.ValueType) bool {
	arrayType, ok := valueType.(zeus_value.ArrayType)
	if !ok {
		// Also check ObjectType with u8[] class name
		if objType, ok := valueType.(zeus_value.ObjectType); ok {
			return objType.Class.Name == "u8[]"
		}
		return false
	}
	intType, ok := arrayType.ElementType.(zeus_value.IntType)
	if !ok {
		return false
	}
	return intType.Size == zeus_value.I8 && !intType.Signed
}

// getOrCreateStringClass returns the string primordial class, creating it if necessary
func (p *TypeCheckingPass) getOrCreateStringClass(tc *TypeChecker, span *token.Span) *zeus_value.Class {
	stringClassName := zeus_value.ZEUS_PRIMORDIAL_STRING
	
	// Check if the string class already exists in the symbol table
	if existingClass, ok := tc.builder.symbolTable.GetSymbol(stringClassName); ok {
		if class := zeus_value.AsClass(existingClass); class != nil {
			return class
		}
	}
	
	// Create the string class definition
	stringClass := zeus_value.GetStringPrimordialClassDefinition(span)
	tc.builder.symbolTable.DeclareSymbol(stringClassName, stringClass)
	
	return stringClass
}

// converts left and right to the same type
func (p *TypeCheckingPass) doImplicitCastToSameType(tc *TypeChecker, instr *Instr, left, right zeus_value.Value) (zeus_value.Value, zeus_value.Value) {
	leftValueType := tc.getValueType(left)
	rightValueType := tc.getValueType(right)
	castErrMsg := fmt.Sprintf("cannot do implicit cast to same type: %s and %s", leftValueType, rightValueType)
	ok := false

	switch leftValueType := leftValueType.(type) {
	case zeus_value.IntType:
		switch rightValueType := rightValueType.(type) {
		case zeus_value.IntType:
			if leftValueType.Size > rightValueType.Size {
				right, ok = p.tryImplicitCast(tc, instr, right, leftValueType)
				if !ok {
					tc.pushError(&zeus_error.ZeusError{
						Message: fmt.Sprintf("cannot cast %s to %s without an explicit cast", rightValueType, leftValueType),
						Span:    instr.Span,
					})
				}
			} else if rightValueType.Size > leftValueType.Size {
				left, ok = p.tryImplicitCast(tc, instr, left, rightValueType)
				if !ok {
					tc.pushError(&zeus_error.ZeusError{
						Message: fmt.Sprintf("cannot cast %s to %s without an explicit cast", leftValueType, rightValueType),
						Span:    instr.Span,
					})
				}
			}
		case zeus_value.FloatType:
			left, ok = p.tryImplicitCast(tc, instr, left, rightValueType)
			zeus_error.Assert(ok, "failed to cast int to float")
		default:
			tc.pushError(&zeus_error.ZeusError{
				Message: castErrMsg,
				Span:    instr.Span,
			})
		}
	case zeus_value.FloatType:
		switch rightValueType := rightValueType.(type) {
		case zeus_value.FloatType:
			if leftValueType.Size > rightValueType.Size {
				right, ok = p.tryImplicitCast(tc, instr, right, leftValueType)
				zeus_error.Assert(ok, "failed to cast smaller float to larger float")
			} else if rightValueType.Size > leftValueType.Size {
				left, ok = p.tryImplicitCast(tc, instr, left, rightValueType)
				zeus_error.Assert(ok, "failed to cast smaller float to larger float")
			}
		case zeus_value.IntType:
			right, ok = p.tryImplicitCast(tc, instr, right, leftValueType)
			zeus_error.Assert(ok, "failed to cast int to float")
		default:
			panic(castErrMsg)
		}
	}

	return left, right
}

func (p *TypeCheckingPass) tcBinaryOp(tc *TypeChecker, instr *Instr, resultTypeFn func(a, b zeus_value.ValueType) zeus_value.ValueType, cmpTypeFn func(a, b zeus_value.ValueType) bool) {
	input := AsBinaryOpInstrInput(instr.Input)

	if !cmpTypeFn(tc.getValueType(input.Left), tc.getValueType(input.Right)) {
		tc.pushError(&zeus_error.ZeusError{
			Message: fmt.Sprintf("invalid operands of type '%s' and '%s' for binary operation", tc.getValueType(input.Left), tc.getValueType(input.Right)),
			Span:    instr.Span,
		})
	} else {
		left, right := p.doImplicitCastToSameType(tc, instr, input.Left, input.Right)
		input.Left = left
		input.Right = right
	}

	instr.Output.ValueType = resultTypeFn(tc.getValueType(input.Left), tc.getValueType(input.Right))
}

func (p *TypeCheckingPass) tcUnaryOp(tc *TypeChecker, instr *Instr, resultTypeFn func(a zeus_value.ValueType) zeus_value.ValueType, cmpTypeFn func(a zeus_value.ValueType) bool) {
	input := AsUnaryOpInstrInput(instr.Input)

	if !cmpTypeFn(tc.getValueType(input.Value)) {
		tc.pushError(&zeus_error.ZeusError{
			Message: fmt.Sprintf("invalid operand of type '%s' for unary operation", tc.getValueType(input.Value)),
			Span:    instr.Span,
		})
	}

	instr.Output.ValueType = resultTypeFn(tc.getValueType(input.Value))
}

func (p *TypeCheckingPass) tcCondJmp(tc *TypeChecker, instr *Instr) {
	input := AsCondJmpInstrInput(instr.Input)

	if !zeus_value.IsBoolType(tc.getValueType(input.Condition)) {
		tc.pushError(&zeus_error.ZeusError{
			Message: fmt.Sprintf("condition must be of type bool, but found %s", tc.getValueType(input.Condition)),
			Span:    instr.Span,
		})
	}
}

func (p *TypeCheckingPass) tcLoad(instr *Instr) {
	input := AsLoadInstrInput(instr.Input)
	instr.Output.ValueType = input.Addr.ValueType
}

func (p *TypeCheckingPass) tcStore(tc *TypeChecker, instr *Instr) {
	input := AsStoreInstrInput(instr.Input)

	if !input.Addr.IsPtr {
		tc.pushError(&zeus_error.ZeusError{
			Message: "invalid lvalue in assignment",
			Span:    instr.Span,
		})
	}

	if input.Addr.IsConst {
		tc.pushError(&zeus_error.ZeusError{
			Message: fmt.Sprintf("cannot assign to constant '%s'", input.Addr.Name),
			Span:    instr.Span,
		})
	}

	// If the variable has no declared type (e.g. ternary result var), infer from stored value.
	if input.Addr.ValueType == nil {
		input.Addr.ValueType = tc.getValueType(input.Value)
		return
	}

	input.Value = p.cmpValueWithImplicitCast(tc, instr, input.Addr.ValueType, input.Value)
}

func (p *TypeCheckingPass) tcReturn(tc *TypeChecker, instr *Instr) {
	input := AsReturnInstrInput(instr.Input)

	if tc.currentFunction == nil {
		tc.pushError(&zeus_error.ZeusError{
			Message: "return statement outside of function",
			Span:    instr.Span,
		})

		return
	}

	returnType := tc.currentFunction.ReturnType

	if zeus_value.IsVoidType(returnType) && input.Value != nil {
		tc.pushError(&zeus_error.ZeusError{
			Message: "cannot return a value from void function",
			Span:    instr.Span,
		})
	} else if !zeus_value.IsVoidType(returnType) && input.Value == nil {
		tc.pushError(&zeus_error.ZeusError{
			Message: fmt.Sprintf("function must return a value of type '%s'", returnType),
			Span:    instr.Span,
		})
	} else if zeus_value.IsVoidType(returnType) && input.Value == nil {
		return
	} else {
		input.Value = p.cmpValueWithImplicitCast(tc, instr, returnType, input.Value)
	}
}

func (p *TypeCheckingPass) tcExport(tc *TypeChecker, instr *Instr) {
	input := AsExportInstrInput(instr.Input)
	valueType := tc.getValueType(input.Value)

	if !zeus_value.IsFunctionType(valueType) && !zeus_value.IsClass(input.Value) {
		tc.pushError(&zeus_error.ZeusError{
			Message: fmt.Sprintf("cannot export value of type '%s'", valueType),
			Span:    instr.Span,
		})
	}
}

func (p *TypeCheckingPass) tcImport(tc *TypeChecker, instr *Instr) {
	input := AsImportInstrInput(instr.Input)
	valueType := tc.getValueType(input.Value)

	if !zeus_value.IsFunctionType(valueType) && !zeus_value.IsClass(input.Value) {
		tc.pushError(&zeus_error.ZeusError{
			Message: fmt.Sprintf("cannot import value of type '%s'", valueType),
			Span:    instr.Span,
		})
	}
}

// tcFunctionCall performs common type checking logic for function calls
// It validates arguments and performs implicit casting based on function signature
func (p *TypeCheckingPass) tcFunctionCall(tc *TypeChecker, instr *Instr, functionType zeus_value.FunctionType, args []zeus_value.Value, calleeSpan *token.Span) []zeus_value.Value {
	if len(args) != len(functionType.ParamTypes) {
		tc.pushError(&zeus_error.ZeusError{
			Message: fmt.Sprintf("expected %d arguments for function, but found %d", len(functionType.ParamTypes), len(args)),
			Span:    calleeSpan,
		})
		return args
	}

	// Perform implicit casting on arguments
	for i := range args {
		castedArg, ok := p.tryImplicitCast(tc, instr, args[i], functionType.ParamTypes[i])
		args[i] = castedArg
		if !ok {
			tc.pushError(&zeus_error.ZeusError{
				Message: fmt.Sprintf("argument %d of type '%s' does not match expected type '%s'", i+1, tc.getValueType(args[i]), functionType.ParamTypes[i]),
				Span:    args[i].GetSpan(),
			})
		}
	}

	return args
}

func (p *TypeCheckingPass) tcCallFunc(tc *TypeChecker, instr *Instr) {
	input := AsCallFuncInstrInput(instr.Input)
	function := zeus_value.AsFunction(input.Callee)

	if function == nil {
		tc.pushError(&zeus_error.ZeusError{
			Message: "expression is not callable",
			Span:    input.Callee.GetSpan(),
		})

		return
	}

	functionType := zeus_value.ToFunctionType(*function)

	// Use the abstracted function call type checking
	input.Args = p.tcFunctionCall(tc, instr, functionType, input.Args, input.Callee.GetSpan())
	instr.Input = NewCallFuncInstrInput(input.Callee, input.Args)

	instr.Output.ValueType = functionType.ReturnType
}

func (p *TypeCheckingPass) tcDeclClass(tc *TypeChecker, instr *Instr) {}

func (p *TypeCheckingPass) tcNewObj(tc *TypeChecker, instr *Instr) {
	input := AsNewObjInstrInput(instr.Input)

	if !zeus_value.IsClass(input.Callee) {
		tc.pushError(&zeus_error.ZeusError{
			Message: fmt.Sprintf("cannot create object of type '%s'", tc.getValueType(input.Callee)),
			Span:    input.Callee.GetSpan(),
		})
	}

	class := zeus_value.AsClass(input.Callee)

	var constructorMethod *zeus_value.Function = nil
	var constructorAccessModifier token.TokenType = token.TokenTypePublic

	for _, method := range class.Methods {
		if method.Method.Name == token.CONSTRUCTOR_METHOD_NAME {
			constructorMethod = method.Method
			if method.AccessModifier != nil {
				constructorAccessModifier = method.AccessModifier.Type
			}
			break
		}
	}

	if constructorMethod == nil && len(input.Args) > 0 {
		tc.pushError(&zeus_error.ZeusError{
			Message: "no constructor method found in class",
			Span:    instr.Output.Span,
		})
	}

	if constructorMethod != nil {
		if constructorAccessModifier == token.TokenTypePrivate {
			tc.pushError(&zeus_error.ZeusError{
				Message: "cannot create object of class with private constructor",
				Span:    instr.Output.Span,
			})
		} else if len(input.Args) != len(constructorMethod.Params) {
			tc.pushError(&zeus_error.ZeusError{
				Message: fmt.Sprintf("expected %d arguments for constructor, but found %d", len(constructorMethod.Params), len(input.Args)),
				Span:    instr.Output.Span,
			})
		} else {
			for i := range input.Args {
				input.Args[i] = p.cmpValueWithImplicitCast(tc, instr, constructorMethod.Params[i].ValueType, input.Args[i])
			}
		}
	}

	instr.Output.ValueType = zeus_value.NewObjectType(*class)
}

func (p *TypeCheckingPass) tcObjectPropertyAccess(tc *TypeChecker, instr *Instr) {
	input := AsObjectPropertyAccessInstrInput(instr.Input)
	output := instr.Output
	valueType := tc.getValueType(input.Object)

	if zeus_value.IsObjectType(valueType) {
		class := zeus_value.AsObjectType(valueType).Class
		properties := class.Properties
		methods := class.Methods
		isFound := false
		isAccessible := false

		for _, property := range properties {
			if property.Property.Name == input.Property {
				isFound = true
				if property.AccessModifier != nil {
					isAccessible = property.AccessModifier.Type == token.TokenTypePublic
				}
				instr.Output.ValueType = property.Property.ValueType
			}
		}

		for _, method := range methods {
			if method.Method.Name == input.Property {
				isFound = true
				if method.AccessModifier != nil {
					isAccessible = method.AccessModifier.Type == token.TokenTypePublic
				}
				instr.Output.ValueType = zeus_value.ToFunctionType(*method.Method)
			}
		}

		if !isFound {
			// Special case: provide a clearer error for string immutability
			if class.Name == zeus_value.ZEUS_PRIMORDIAL_STRING && input.Property == zeus_value.ARRAY_METHOD_SET {
				tc.pushError(&zeus_error.ZeusError{
					Message: "cannot assign to string index: strings are immutable",
					Span:    output.Span,
				})
			} else {
				tc.pushError(&zeus_error.ZeusError{
					Message: fmt.Sprintf("property %s not found in class %s", input.Property, class.Name),
					Span:    output.Span,
				})
			}
		}

		if input.Property == token.CONSTRUCTOR_METHOD_NAME {
			tc.pushError(&zeus_error.ZeusError{
				Message: "cannot access constructor method of a class",
				Span:    output.Span,
			})
		} else {
			propertyOfSameClass := tc.currentClass != nil && tc.currentClass.Name == class.Name
			if !isAccessible && !propertyOfSameClass {
				tc.pushError(&zeus_error.ZeusError{
					Message: fmt.Sprintf("property %s is not accessible in class %s", input.Property, class.Name),
					Span:    output.Span,
				})
			}
		}
	} else {
		tc.pushError(&zeus_error.ZeusError{
			Message: fmt.Sprintf("cannot access property %s of type '%s'", input.Property, valueType),
			Span:    output.Span,
		})
	}
}

func (p *TypeCheckingPass) tcGetIndex(tc *TypeChecker, instr *Instr) {
	input := AsGetIndexInstrInput(instr.Input)
	output := instr.Output
	targetType := tc.getValueType(input.Array)

	// Check that the value being indexed is an object type (array or string)
	if !zeus_value.IsObjectType(targetType) {
		tc.pushError(&zeus_error.ZeusError{
			Message: fmt.Sprintf("cannot use indexing operator [] on type '%s', expected an array or string", targetType),
			Span:    instr.Span,
		})
		return
	}

	objType := zeus_value.AsObjectType(targetType)

	// Check if this is a string (string indexing returns u8)
	if objType.Class.Name == zeus_value.ZEUS_PRIMORDIAL_STRING {
		// String indexing only supports a single index
		if len(input.Indices) != 1 {
			tc.pushError(&zeus_error.ZeusError{
				Message: "string indexing only supports a single index",
				Span:    instr.Span,
			})
			return
		}

		// Validate index is an integer type
		indexType := tc.getValueType(input.Indices[0])
		if !zeus_value.IsIntType(indexType) {
			tc.pushError(&zeus_error.ZeusError{
				Message: fmt.Sprintf("string index must be an integer, got '%s'", indexType),
				Span:    instr.Span,
			})
		}

		// String indexing returns u8 (unsigned byte)
		output.ValueType = zeus_value.IntType{Size: zeus_value.I8, Signed: false, Span: instr.Span}
		return
	}

	// Check if this is actually an array class (has ArrayElementType)
	if objType.Class.ArrayElementType == nil {
		tc.pushError(&zeus_error.ZeusError{
			Message: fmt.Sprintf("cannot use indexing operator [] on type '%s', expected an array or string", objType.Class.Name),
			Span:    instr.Span,
		})
		return
	}

	// Validate each index is an integer type
	for _, index := range input.Indices {
		indexType := tc.getValueType(index)
		if !zeus_value.IsIntType(indexType) {
			tc.pushError(&zeus_error.ZeusError{
				Message: fmt.Sprintf("array index must be an integer, got '%s'", indexType),
				Span:    instr.Span,
			})
		}
	}

	// Determine the result type by peeling off array dimensions
	// For array[i][j], we need to peel off one dimension per index
	resultType := targetType
	for range input.Indices {
		if objType := zeus_value.AsObjectType(resultType); objType != nil && objType.Class.ArrayElementType != nil {
			resultType = objType.Class.ArrayElementType
		} else {
			tc.pushError(&zeus_error.ZeusError{
				Message: fmt.Sprintf("too many indices for array type '%s'", targetType),
				Span:    instr.Span,
			})
			return
		}
	}

	// If the result is still an array type, wrap it in ObjectType
	if arrayResultType, ok := resultType.(zeus_value.ArrayType); ok {
		resultClass := tc.getClassFromArrayType(arrayResultType)
		resultType = zeus_value.NewObjectType(*resultClass)
	}

	output.ValueType = resultType
}


func (p *TypeCheckingPass) tcIndirectFuncCall(tc *TypeChecker, instr *Instr) {
	input := AsIndirectFuncCallInstrInput(instr.Input)

	methodType := tc.getValueType(input.Function)
	functionType := zeus_value.AsFunctionType(methodType)

	if functionType == nil {
		tc.pushError(&zeus_error.ZeusError{
			Message: "expression is not callable",
			Span:    instr.Output.Span,
		})
		return
	}

	input.Args = p.tcFunctionCall(tc, instr, *functionType, input.Args, input.Function.GetSpan())
	instr.Input = NewIndirectFuncCallInstrInput(input.Function, input.Args)

	instr.Output.ValueType = functionType.ReturnType
}

func (p *TypeCheckingPass) tcDeclClassMethod(tc *TypeChecker, instr *Instr) {
	input := AsDeclClassMethodInstrInput(instr.Input)
	p.validateFunctionReturns(tc, input.Method, input.Body)
}

// tcThrow validates that the thrown expression is an Error class or subclass
func (p *TypeCheckingPass) tcThrow(tc *TypeChecker, instr *Instr) {
	input := AsThrowInstrInput(instr.Input)
	objectPtr := input.ObjectPtr

	// Get the type of the thrown value
	valueType := tc.getValueType(objectPtr)

	// Check if it's an object type
	if !zeus_value.IsObjectType(valueType) {
		tc.pushError(&zeus_error.ZeusError{
			Message: fmt.Sprintf("throw expression must be an Error or subclass, but found '%s'", valueType),
			Span:    instr.Span,
		})
		return
	}

	// Check if the class is Error or a subclass of Error
	objectType := zeus_value.AsObjectType(valueType)
	if objectType == nil {
		tc.pushError(&zeus_error.ZeusError{
			Message: fmt.Sprintf("throw expression must be an Error or subclass, but found '%s'", valueType),
			Span:    instr.Span,
		})
		return
	}

	if !zeus_value.IsErrorClass(&objectType.Class) {
		tc.pushError(&zeus_error.ZeusError{
			Message: fmt.Sprintf("throw expression must be an Error or subclass, but found class '%s'", objectType.Class.Name),
			Span:    instr.Span,
		})
	}
}

// UnusedWarningPass generates warnings for unused identifiers
// This pass should run last after all usage tracking is complete
type UnusedWarningPass struct{
	primordialFunctions []*zeus_value.Function
}

func NewUnusedWarningPass() *UnusedWarningPass {
	return &UnusedWarningPass{
		primordialFunctions: []*zeus_value.Function{},
	}
}

func (p *UnusedWarningPass) GetName() string {
	return "UnusedWarningPass"
}

// markValueAsUsed marks a value (Var or Function) as used if applicable
func markValueAsUsed(value zeus_value.Value) {
	if v := zeus_value.AsVar(value); v != nil {
		v.IsUsed = true
	} else if f := zeus_value.AsFunction(value); f != nil {
		f.IsUsed = true
	}
}

func (p *UnusedWarningPass) HandleInstruction(tc *TypeChecker, instr *Instr) {
	switch instr.Type {
	case InstrTypeDeclVar:
		p.handleVarDecl(instr)
	case InstrTypeStore:
		p.handleStore(instr)
	case InstrTypeLoad:
		p.handleLoad(instr)
	case InstrTypeAdd, InstrTypeSub, InstrTypeMul, InstrTypeDiv, InstrTypeMod, InstrTypePower,
		InstrTypeEqEq, InstrTypeNotEq, InstrTypeLessThan, InstrTypeGreaterThan,
		InstrTypeLessThanEq, InstrTypeGreaterThanEq, InstrTypeAnd, InstrTypeOr,
		InstrTypeBitAnd, InstrTypeBitOr, InstrTypeBitXor, InstrTypeShl, InstrTypeShr:
		p.handleBinaryOp(instr)
	case InstrTypeNot, InstrTypeNeg, InstrTypeBitNot:
		p.handleUnaryOp(instr)
	case InstrTypeCallFunc:
		p.handleCallFunc(instr)
	case InstrTypeIndirectFuncCall:
		p.handleIndirectFuncCall(instr)
	case InstrTypeReturn:
		p.handleReturn(instr)
	case InstrTypeCondJmp:
		p.handleCondJmp(instr)
	case InstrTypeNewObj:
		p.handleNewObj(instr)
	case InstrTypeObjectPropertyAccess:
		p.handleObjectPropertyAccess(tc, instr)
	case InstrTypeDeclPrimordialFunc:
		p.handleDeclPrimordialFunc(instr)
	case InstrTypeExport:
		p.handleExport(instr)
	case InstrTypeGetIndex:
		p.handleGetIndex(instr)
	}
}

func (p *UnusedWarningPass) handleDeclPrimordialFunc(instr *Instr) {
	input := AsDeclPrimordialFuncInstrInput(instr.Input)
	p.primordialFunctions = append(p.primordialFunctions, input.Function)
}

// handleVarDecl processes variable declarations and marks initializers as used
func (p *UnusedWarningPass) handleVarDecl(instr *Instr) {
	input := AsDeclVarInstrInput(instr.Input)
	if input.Initializer != nil {
		markValueAsUsed(input.Initializer)
	}
}

// handleStore processes variable assignments and marks values as used
func (p *UnusedWarningPass) handleStore(instr *Instr) {
	input := AsStoreInstrInput(instr.Input)
	markValueAsUsed(input.Value)
}

// handleLoad processes variable usage and marks variables as used
func (p *UnusedWarningPass) handleLoad(instr *Instr) {
	input := AsLoadInstrInput(instr.Input)

	// Mark the variable as used
	input.Addr.IsUsed = true
}

// handleBinaryOp processes binary operations and marks operands as used
func (p *UnusedWarningPass) handleBinaryOp(instr *Instr) {
	input := AsBinaryOpInstrInput(instr.Input)
	markValueAsUsed(input.Left)
	markValueAsUsed(input.Right)
}

// handleUnaryOp processes unary operations and marks the operand as used
func (p *UnusedWarningPass) handleUnaryOp(instr *Instr) {
	input := AsUnaryOpInstrInput(instr.Input)
	markValueAsUsed(input.Value)
}

// handleCallFunc processes function calls and marks arguments as used
func (p *UnusedWarningPass) handleCallFunc(instr *Instr) {
	input := AsCallFuncInstrInput(instr.Input)
	markValueAsUsed(input.Callee)
	markValuesAsUsed(input.Args)
}

// markValuesAsUsed marks all values in a slice as used
func markValuesAsUsed(values []zeus_value.Value) {
	for _, v := range values {
		markValueAsUsed(v)
	}
}

// handleIndirectFuncCall processes indirect function calls and marks the function and arguments as used
func (p *UnusedWarningPass) handleIndirectFuncCall(instr *Instr) {
	input := AsIndirectFuncCallInstrInput(instr.Input)
	markValueAsUsed(input.Function)
	markValuesAsUsed(input.Args)
}

// handleReturn processes return statements and marks the return value as used
func (p *UnusedWarningPass) handleReturn(instr *Instr) {
	input := AsReturnInstrInput(instr.Input)
	markValueAsUsed(input.Value)
}

// handleCondJmp processes conditional jumps and marks the condition as used
func (p *UnusedWarningPass) handleCondJmp(instr *Instr) {
	input := AsCondJmpInstrInput(instr.Input)

	// Mark the condition as used
	if condVar := zeus_value.AsVar(input.Condition); condVar != nil {
		condVar.IsUsed = true
	}
}

// handleNewObj processes new object expressions and marks the class as used
func (p *UnusedWarningPass) handleNewObj(instr *Instr) {
	input := AsNewObjInstrInput(instr.Input)
	if class := zeus_value.AsClass(input.Callee); class != nil {
		class.IsUsed = true
	}
	markValuesAsUsed(input.Args)
}

// handleObjectPropertyAccess processes object property accesses and marks the object as used
// Also marks class methods and properties as used when they are accessed
func (p *UnusedWarningPass) handleObjectPropertyAccess(tc *TypeChecker, instr *Instr) {
	input := AsObjectPropertyAccessInstrInput(instr.Input)

	// Mark the object as used
	if objectVar := zeus_value.AsVar(input.Object); objectVar != nil {
		objectVar.IsUsed = true
	}

	// Mark class methods and properties as used when accessed
	objectType := tc.getValueType(input.Object)

	// Check if it's an object type (class instance)
	if zeus_value.IsObjectType(objectType) {
		class := zeus_value.AsObjectType(objectType).Class
		// Look for a method with the matching name
		for _, classMethod := range class.Methods {
			if classMethod.Method.Name == input.Property {
				// Mark the method as used
				classMethod.Method.IsUsed = true
				return
			}
		}

		// Look for a property with the matching name
		for _, classProperty := range class.Properties {
			if classProperty.Property.Name == input.Property {
				// Mark the property as used
				classProperty.Property.IsUsed = true
				return
			}
		}
	}
}

// handleExport processes export statements and marks exported functions as used
func (p *UnusedWarningPass) handleExport(instr *Instr) {
	input := AsExportInstrInput(instr.Input)

	// Mark exported functions as used
	if function := zeus_value.AsFunction(input.Value); function != nil {
		function.IsUsed = true
	}

	// Mark exported classes as used
	if class := zeus_value.AsClass(input.Value); class != nil {
		class.IsUsed = true
	}
}

func (p *UnusedWarningPass) handleGetIndex(instr *Instr) {
	input := AsGetIndexInstrInput(instr.Input)

	// Mark the array as used
	if arrayVar := zeus_value.AsVar(input.Array); arrayVar != nil {
		arrayVar.IsUsed = true
	}

	// Mark all index variables as used
	for _, index := range input.Indices {
		if indexVar := zeus_value.AsVar(index); indexVar != nil {
			indexVar.IsUsed = true
		}
	}
}

func (p *UnusedWarningPass) Finalize(tc *TypeChecker) {
	// Check for unused variables, functions, classes, and class members - push warnings
	tc.builder.symbolTable.Walk(func(name string, value zeus_value.Value) {
		if variable := zeus_value.AsVar(value); variable != nil {
			// Skip temporary variables as they shouldn't generate warnings
			if !variable.IsTempVariable() && !variable.IsUsed {
				tc.pushError(&zeus_error.ZeusError{
					Severity: zeus_error.ErrorSeverityWarning,
					Message:  fmt.Sprintf("identifier '%s' is declared but not used", variable.Name),
					Span:     variable.Span,
				})
			}
		} else if function := zeus_value.AsFunction(value); function != nil {
			// ignore unused primordial functions
			for _, primordialFunction := range p.primordialFunctions {
				if function.Name == primordialFunction.Name {
					return
				}
			}
			isMainFunction := function.Name == token.MAIN_FUNCTION_NAME && tc.IsEntryPoint
			// Check for unused functions, ignore class methods
			if !function.IsUsed && !strings.Contains(function.Name, ".") && !isMainFunction {
				tc.pushError(&zeus_error.ZeusError{
					Severity: zeus_error.ErrorSeverityWarning,
					Message:  fmt.Sprintf("function '%s' is declared but not used", function.Name),
					Span:     function.Span,
				})
			}
		} else if class := zeus_value.AsClass(value); class != nil {
			// Check if the class is unused (no objects created from it)
			if !class.IsUsed && class.PrimordialName == "" {
				tc.pushError(&zeus_error.ZeusError{
					Severity: zeus_error.ErrorSeverityWarning,
					Message:  fmt.Sprintf("class '%s' is declared but not used", class.Name),
					Span:     class.Span,
				})
			} else {
				// Only check class members if the class itself is used
				// Check all methods in this class
				for _, classMethod := range class.Methods {
					method := classMethod.Method

					// Skip constructor methods as they're implicitly used
					if method.Name == token.CONSTRUCTOR_METHOD_NAME {
						continue
					}

					// Check if the method is unused
					if !method.IsUsed && class.PrimordialName == "" {
						tc.pushError(&zeus_error.ZeusError{
							Severity: zeus_error.ErrorSeverityWarning,
							Message:  fmt.Sprintf("method '%s' in class '%s' is declared but not used", method.Name, class.Name),
							Span:     method.Span,
						})
					}
				}

				// Check all properties in this class
				for _, classProperty := range class.Properties {
					property := classProperty.Property

					// Check if the property is unused
					if !property.IsUsed && class.PrimordialName == "" {
						tc.pushError(&zeus_error.ZeusError{
							Severity: zeus_error.ErrorSeverityWarning,
							Message:  fmt.Sprintf("property '%s' in class '%s' is declared but not used", property.Name, class.Name),
							Span:     property.Span,
						})
					}
				}
			}
		}
	})
}
