// First-class boxed numeric types. For each primitive scalar `t` there is a boxed, object form `T`
// (Java-style: `i32` is the primitive, `I32` its boxed object). A scalar autoboxes into the box
// matching its exact type, so toString, round-trips, and arithmetic on the concrete type stay
// type-exact (no f64 collapse). Each box also structurally satisfies the `Number` umbrella interface
// (toString + valueOf), so a boxed number can be held/printed polymorphically as a `Number` — at
// which point valueOf() widens to f64 (the deliberate price of erasing the concrete type).
// Bodies are extern (prelude bodies are dropped); the runtime functions are generated by a comptime
// loop in number_runtime.zig. Booleans use the concrete `Bool` (prelude/bool.zs).

// The umbrella every numeric box structurally satisfies (they all declare toString + valueOf). Hold
// a boxed number polymorphically as `Number`; valueOf() widens to f64 when the concrete type is
// erased. Interfaces emit no IR — loadPreludes harvests this from the compiled prelude symbol table.
interface Number {
    toString(): string;
    valueOf(): f64;
}

class I8 {
    private value: i8;
    @extern("zeus_box_i8_toString") public toString(): string;
    @extern("zeus_box_i8_valueOf") public valueOf(): f64;
}

class I16 {
    private value: i16;
    @extern("zeus_box_i16_toString") public toString(): string;
    @extern("zeus_box_i16_valueOf") public valueOf(): f64;
}

class I32 {
    private value: i32;
    @extern("zeus_box_i32_toString") public toString(): string;
    @extern("zeus_box_i32_valueOf") public valueOf(): f64;
}

class I64 {
    private value: i64;
    @extern("zeus_box_i64_toString") public toString(): string;
    @extern("zeus_box_i64_valueOf") public valueOf(): f64;
}

class U8 {
    private value: u8;
    @extern("zeus_box_u8_toString") public toString(): string;
    @extern("zeus_box_u8_valueOf") public valueOf(): f64;
}

class U16 {
    private value: u16;
    @extern("zeus_box_u16_toString") public toString(): string;
    @extern("zeus_box_u16_valueOf") public valueOf(): f64;
}

class U32 {
    private value: u32;
    @extern("zeus_box_u32_toString") public toString(): string;
    @extern("zeus_box_u32_valueOf") public valueOf(): f64;
}

class U64 {
    private value: u64;
    @extern("zeus_box_u64_toString") public toString(): string;
    @extern("zeus_box_u64_valueOf") public valueOf(): f64;
}

class F32 {
    private value: f32;
    @extern("zeus_box_f32_toString") public toString(): string;
    @extern("zeus_box_f32_valueOf") public valueOf(): f64;
}

class F64 {
    private value: f64;
    @extern("zeus_box_f64_toString") public toString(): string;
    @extern("zeus_box_f64_valueOf") public valueOf(): f64;
}
